name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt
      PG_USER:     ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_DB:       ${{ secrets.PG_DB }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: analytics
          POSTGRES_PASSWORD: analytics
          POSTGRES_DB: analytics
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U analytics -d analytics"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt-postgres
        run: pip install "dbt-postgres==1.10.*"

      - name: Run dbt (seed/run/test)
        run: |
          dbt seed --full-refresh
          dbt run
          dbt test